server:
  port: 8000

mybatis:
  mapper-locations: classpath:com/gao/cloud/dao/*Dao.xml


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


logging:
  level:
    root: INFO
    org.mybatis: debug
    com.gao.cloud: debug

management:
  security:
    enabled: false

